FROM java:openjdk-8u91-jdk
CMD java -jar *.jar
EXPOSE 8080
ENV VERSION=0.15.0
RUN wget --quiet https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/local/java/eventuate-local-java-cdc-service/${VERSION}.RELEASE/eventuate-local-java-cdc-service-${VERSION}.RELEASE.jar
