FROM java:openjdk-8u91-jdk
CMD java -jar *.jar
EXPOSE 8080
RUN wget --quiet https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/local/java/eventuate-local-java-cdc-service/0.12.3.RELEASE/eventuate-local-java-cdc-service-0.12.3.RELEASE.jar
