FROM java:openjdk-8u91-jdk
CMD java -jar *.jar
EXPOSE 8080
RUN wget --quiet http://mavenrepo.eventuate.io/release/io/eventuate/local/java/eventuate-local-java-cdc-service/0.6.0.RELEASE/eventuate-local-java-cdc-service-0.6.0.RELEASE.jar
